/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class iforce2d_buoyancy_BuoyancyFunctions */

#ifndef _Included_iforce2d_buoyancy_BuoyancyFunctions
#define _Included_iforce2d_buoyancy_BuoyancyFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     iforce2d_buoyancy_BuoyancyFunctions
 * Method:    doWork
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_iforce2d_buoyancy_BuoyancyFunctions_doWork
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
